### ISSUE TITLE
Falta concluir o desenvolvimento do pacote

### ISSUE THREAD

**Issue by Artenes** [luisdalmolin/e-rede-php#1]
Olá! Me chamo Artenes e também tenho de integrar o e.Rede à uma aplicação em Laravel. Gostaria de saber se tu vai continuar com este projeto ou se você vai abandonar ele? Estaria interessado em saber na forma como você estava pensando em fazer essa integração e de que forma poderia ajudar a fazer ela?

Uma coisa que recomendaria fazer seria criar dois pacotes: um em php puro com a integração com o e.Rede e outro para pegar esse pacote e integrar ele com o Laravel, Assim possibilitando que esse pacote possa ser usado em qualquer projeto que use PHP mas não use Laravel.

**Comment by luisdalmolin** [comment]
Olá!

Sim, na verdade este pacote será agnóstico, ou seja, para usar em qualquer framework e/ou ambiente.

Eu ainda não dei início em definitivo nele, pois vou fazer conforme uma demanda de um cliente que deve ser liberada nos próximos dias.

Não posso dar um prazo de quando vai ficar pronto nem se vai possui todas as funcionalidades estarão disponíveis neste pacote, mas o desenvolvimento deve iniciar no início do próximo mês.
